spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: gateway
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true
    gateway:
      discovery:
        locator:
          enabled: false  # Active la découverte des services via Eureka
          lower-case-service-id: true  #convertit les noms de service en minuscule
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gateway"
    description: "gateway which communicate with all microservice"

user-service:
  url: http://localhost:3001

web:
  url: http://localhost:4200

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 4
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000