spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Active la découverte des services via Eureka
          lower-case-service-id: true  #convertit les noms de service en minuscule

server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gateway"
    description: "gateway which communicate with all microservice"